/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import java.awt.event.WindowEvent;

/**
 *
 * @author Clayton
 */
public class UserFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserFrame
     */
    public UserFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        wrtPubMsgPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        wrtPvtMsgPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        readPvtMsgPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        readPubMsgPanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        hashtagSearchPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        hashtagField = new javax.swing.JTextField();
        hashtagSearchButton = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jButton9 = new javax.swing.JButton();
        youFollowPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jButton10 = new javax.swing.JButton();
        followYouPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList<>();
        jButton11 = new javax.swing.JButton();
        addFollowPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        logOutMenu = new javax.swing.JMenuItem();
        writeMenu = new javax.swing.JMenu();
        wrtPubMsgMenu = new javax.swing.JMenuItem();
        wrtPvtMsgMenu = new javax.swing.JMenuItem();
        readMenu = new javax.swing.JMenu();
        readYourMsgMenu = new javax.swing.JMenuItem();
        readPubMsgMenu = new javax.swing.JMenuItem();
        hashtagSearchMenu = new javax.swing.JMenuItem();
        followMenu = new javax.swing.JMenu();
        youFollowMenu = new javax.swing.JMenuItem();
        followYouMenu = new javax.swing.JMenuItem();
        addFollowMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Message App - Main Menu");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jDesktopPane1.setMaximumSize(new java.awt.Dimension(800, 600));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(800, 600));
        jDesktopPane1.setOpaque(false);

        wrtPubMsgPanel.setEnabled(false);
        wrtPubMsgPanel.setMaximumSize(new java.awt.Dimension(800, 579));
        wrtPubMsgPanel.setMinimumSize(new java.awt.Dimension(800, 579));
        wrtPubMsgPanel.setVisible(false);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Send");

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout wrtPubMsgPanelLayout = new javax.swing.GroupLayout(wrtPubMsgPanel);
        wrtPubMsgPanel.setLayout(wrtPubMsgPanelLayout);
        wrtPubMsgPanelLayout.setHorizontalGroup(
            wrtPubMsgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrtPubMsgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wrtPubMsgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wrtPubMsgPanelLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        wrtPubMsgPanelLayout.setVerticalGroup(
            wrtPubMsgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrtPubMsgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(wrtPubMsgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(443, Short.MAX_VALUE))
        );

        wrtPvtMsgPanel.setEnabled(false);
        wrtPvtMsgPanel.setMaximumSize(new java.awt.Dimension(800, 579));
        wrtPvtMsgPanel.setMinimumSize(new java.awt.Dimension(800, 579));
        wrtPvtMsgPanel.setVisible(false);

        jLabel1.setText("Send to:");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton3.setText("Send");

        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout wrtPvtMsgPanelLayout = new javax.swing.GroupLayout(wrtPvtMsgPanel);
        wrtPvtMsgPanel.setLayout(wrtPvtMsgPanelLayout);
        wrtPvtMsgPanelLayout.setHorizontalGroup(
            wrtPvtMsgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrtPvtMsgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wrtPvtMsgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(wrtPvtMsgPanelLayout.createSequentialGroup()
                        .addGroup(wrtPvtMsgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(wrtPvtMsgPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(wrtPvtMsgPanelLayout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 495, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wrtPvtMsgPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
        );
        wrtPvtMsgPanelLayout.setVerticalGroup(
            wrtPvtMsgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrtPvtMsgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wrtPvtMsgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(wrtPvtMsgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(412, Short.MAX_VALUE))
        );

        readPvtMsgPanel.setEnabled(false);
        readPvtMsgPanel.setMaximumSize(new java.awt.Dimension(800, 579));
        readPvtMsgPanel.setMinimumSize(new java.awt.Dimension(800, 579));
        readPvtMsgPanel.setVisible(false);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        jLabel2.setText("Written by: NAME");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        jButton5.setText("Close");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout readPvtMsgPanelLayout = new javax.swing.GroupLayout(readPvtMsgPanel);
        readPvtMsgPanel.setLayout(readPvtMsgPanelLayout);
        readPvtMsgPanelLayout.setHorizontalGroup(
            readPvtMsgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(readPvtMsgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(readPvtMsgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, readPvtMsgPanelLayout.createSequentialGroup()
                .addContainerGap(355, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(355, 355, 355))
        );
        readPvtMsgPanelLayout.setVerticalGroup(
            readPvtMsgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(readPvtMsgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jButton5)
                .addContainerGap(282, Short.MAX_VALUE))
        );

        readPubMsgPanel.setEnabled(false);
        readPubMsgPanel.setMaximumSize(new java.awt.Dimension(800, 579));
        readPubMsgPanel.setMinimumSize(new java.awt.Dimension(800, 579));
        readPubMsgPanel.setVisible(false);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList2);

        jLabel3.setText("Written by: NAME");

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane6.setViewportView(jTextArea4);

        jButton6.setText("Reply");

        jButton7.setText("Close");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout readPubMsgPanelLayout = new javax.swing.GroupLayout(readPubMsgPanel);
        readPubMsgPanel.setLayout(readPubMsgPanelLayout);
        readPubMsgPanelLayout.setHorizontalGroup(
            readPubMsgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(readPubMsgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(readPubMsgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane6)
                    .addGroup(readPubMsgPanelLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(205, 205, 205)))
                .addContainerGap())
        );
        readPubMsgPanelLayout.setVerticalGroup(
            readPubMsgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(readPubMsgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(readPubMsgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap(282, Short.MAX_VALUE))
        );

        hashtagSearchPanel.setEnabled(false);
        hashtagSearchPanel.setMaximumSize(new java.awt.Dimension(800, 579));
        hashtagSearchPanel.setMinimumSize(new java.awt.Dimension(800, 579));
        hashtagSearchPanel.setVisible(false);

        jLabel4.setText("Search by this hashtag:");

        hashtagSearchButton.setText("Search");

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(jList3);

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane8.setViewportView(jTextArea5);

        jButton9.setText("Close");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout hashtagSearchPanelLayout = new javax.swing.GroupLayout(hashtagSearchPanel);
        hashtagSearchPanel.setLayout(hashtagSearchPanelLayout);
        hashtagSearchPanelLayout.setHorizontalGroup(
            hashtagSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hashtagSearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hashtagSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hashtagSearchPanelLayout.createSequentialGroup()
                        .addGroup(hashtagSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7)
                            .addComponent(jScrollPane8))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hashtagSearchPanelLayout.createSequentialGroup()
                        .addGap(0, 186, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(hashtagField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hashtagSearchButton)
                        .addGap(198, 198, 198))))
            .addGroup(hashtagSearchPanelLayout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        hashtagSearchPanelLayout.setVerticalGroup(
            hashtagSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hashtagSearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hashtagSearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hashtagField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hashtagSearchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9)
                .addContainerGap(261, Short.MAX_VALUE))
        );

        youFollowPanel.setEnabled(false);
        youFollowPanel.setMaximumSize(new java.awt.Dimension(800, 579));
        youFollowPanel.setMinimumSize(new java.awt.Dimension(800, 579));
        youFollowPanel.setVisible(false);

        jLabel5.setText("You are following:");

        jList4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9.setViewportView(jList4);

        jButton10.setText("Close");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout youFollowPanelLayout = new javax.swing.GroupLayout(youFollowPanel);
        youFollowPanel.setLayout(youFollowPanelLayout);
        youFollowPanelLayout.setHorizontalGroup(
            youFollowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(youFollowPanelLayout.createSequentialGroup()
                .addGroup(youFollowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(youFollowPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane9))
                    .addGroup(youFollowPanelLayout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 340, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(youFollowPanelLayout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        youFollowPanelLayout.setVerticalGroup(
            youFollowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(youFollowPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton10)
                .addContainerGap(379, Short.MAX_VALUE))
        );

        followYouPanel.setEnabled(false);
        followYouPanel.setMaximumSize(new java.awt.Dimension(800, 579));
        followYouPanel.setMinimumSize(new java.awt.Dimension(800, 579));
        followYouPanel.setVisible(false);

        jLabel6.setText("You are being followed by:");

        jList5.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane10.setViewportView(jList5);

        jButton11.setText("Close");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout followYouPanelLayout = new javax.swing.GroupLayout(followYouPanel);
        followYouPanel.setLayout(followYouPanelLayout);
        followYouPanelLayout.setHorizontalGroup(
            followYouPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(followYouPanelLayout.createSequentialGroup()
                .addGroup(followYouPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(followYouPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane10))
                    .addGroup(followYouPanelLayout.createSequentialGroup()
                        .addGroup(followYouPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(followYouPanelLayout.createSequentialGroup()
                                .addGap(355, 355, 355)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(followYouPanelLayout.createSequentialGroup()
                                .addGap(325, 325, 325)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 315, Short.MAX_VALUE)))
                .addContainerGap())
        );
        followYouPanelLayout.setVerticalGroup(
            followYouPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(followYouPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton11)
                .addContainerGap(379, Short.MAX_VALUE))
        );

        addFollowPanel.setEnabled(false);
        addFollowPanel.setMaximumSize(new java.awt.Dimension(800, 579));
        addFollowPanel.setMinimumSize(new java.awt.Dimension(800, 579));
        addFollowPanel.setVisible(false);

        jLabel7.setText("Enter the username of who you'd like to follow:");

        jButton12.setText("Add");

        jButton13.setText("Close");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addFollowPanelLayout = new javax.swing.GroupLayout(addFollowPanel);
        addFollowPanel.setLayout(addFollowPanelLayout);
        addFollowPanelLayout.setHorizontalGroup(
            addFollowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFollowPanelLayout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addGroup(addFollowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addFollowPanelLayout.createSequentialGroup()
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(229, 229, 229))
                    .addGroup(addFollowPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166))))
        );
        addFollowPanelLayout.setVerticalGroup(
            addFollowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFollowPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addFollowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(addFollowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton12)
                    .addComponent(jButton13))
                .addContainerGap(507, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(wrtPubMsgPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(wrtPvtMsgPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(readPvtMsgPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(readPubMsgPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(hashtagSearchPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(youFollowPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(followYouPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(addFollowPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wrtPubMsgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(wrtPvtMsgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(readPvtMsgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(readPubMsgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(hashtagSearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(youFollowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(followYouPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(addFollowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(wrtPubMsgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wrtPvtMsgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(readPvtMsgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(readPubMsgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hashtagSearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(youFollowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(followYouPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addFollowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fileMenu.setText("File");

        logOutMenu.setText("Log Out");
        logOutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutMenuActionPerformed(evt);
            }
        });
        fileMenu.add(logOutMenu);

        jMenuBar1.add(fileMenu);

        writeMenu.setText("Write");

        wrtPubMsgMenu.setText("Public Msg");
        wrtPubMsgMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrtPubMsgMenuActionPerformed(evt);
            }
        });
        writeMenu.add(wrtPubMsgMenu);

        wrtPvtMsgMenu.setText("Private Msg");
        wrtPvtMsgMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrtPvtMsgMenuActionPerformed(evt);
            }
        });
        writeMenu.add(wrtPvtMsgMenu);

        jMenuBar1.add(writeMenu);

        readMenu.setText("Read");

        readYourMsgMenu.setText("Your Msgs");
        readYourMsgMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readYourMsgMenuActionPerformed(evt);
            }
        });
        readMenu.add(readYourMsgMenu);

        readPubMsgMenu.setText("Public Msgs");
        readPubMsgMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readPubMsgMenuActionPerformed(evt);
            }
        });
        readMenu.add(readPubMsgMenu);

        hashtagSearchMenu.setText("By Hashtag");
        hashtagSearchMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hashtagSearchMenuActionPerformed(evt);
            }
        });
        readMenu.add(hashtagSearchMenu);

        jMenuBar1.add(readMenu);

        followMenu.setText("Follow");

        youFollowMenu.setText("Your Follows");
        youFollowMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                youFollowMenuActionPerformed(evt);
            }
        });
        followMenu.add(youFollowMenu);

        followYouMenu.setText("Following You");
        followYouMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followYouMenuActionPerformed(evt);
            }
        });
        followMenu.add(followYouMenu);

        addFollowMenu.setText("Add Follow");
        addFollowMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFollowMenuActionPerformed(evt);
            }
        });
        followMenu.add(addFollowMenu);

        jMenuBar1.add(followMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logOutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutMenuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_logOutMenuActionPerformed

    private void wrtPubMsgMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrtPubMsgMenuActionPerformed
        wrtPubMsgPanel.setVisible(true);
        writeMenu.setEnabled(false);
        readMenu.setEnabled(false);
        followMenu.setEnabled(false);
    }//GEN-LAST:event_wrtPubMsgMenuActionPerformed

    private void wrtPvtMsgMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrtPvtMsgMenuActionPerformed
        wrtPvtMsgPanel.setVisible(true);
        writeMenu.setEnabled(false);
        readMenu.setEnabled(false);
        followMenu.setEnabled(false);
    }//GEN-LAST:event_wrtPvtMsgMenuActionPerformed

    private void readYourMsgMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readYourMsgMenuActionPerformed
        readPvtMsgPanel.setVisible(true);
        writeMenu.setEnabled(false);
        readMenu.setEnabled(false);
        followMenu.setEnabled(false);
    }//GEN-LAST:event_readYourMsgMenuActionPerformed

    private void readPubMsgMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readPubMsgMenuActionPerformed
        readPubMsgPanel.setVisible(true);
        writeMenu.setEnabled(false);
        readMenu.setEnabled(false);
        followMenu.setEnabled(false);
    }//GEN-LAST:event_readPubMsgMenuActionPerformed

    private void hashtagSearchMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hashtagSearchMenuActionPerformed
        hashtagSearchPanel.setVisible(true);
        writeMenu.setEnabled(false);
        readMenu.setEnabled(false);
        followMenu.setEnabled(false);
    }//GEN-LAST:event_hashtagSearchMenuActionPerformed

    private void youFollowMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_youFollowMenuActionPerformed
        youFollowPanel.setVisible(true);
        writeMenu.setEnabled(false);
        readMenu.setEnabled(false);
        followMenu.setEnabled(false);
    }//GEN-LAST:event_youFollowMenuActionPerformed

    private void followYouMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_followYouMenuActionPerformed
        followYouPanel.setVisible(true);
        writeMenu.setEnabled(false);
        readMenu.setEnabled(false);
        followMenu.setEnabled(false);
    }//GEN-LAST:event_followYouMenuActionPerformed

    private void addFollowMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFollowMenuActionPerformed
        addFollowPanel.setVisible(true);
        writeMenu.setEnabled(false);
        readMenu.setEnabled(false);
        followMenu.setEnabled(false);
    }//GEN-LAST:event_addFollowMenuActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        wrtPubMsgPanel.setVisible(false);
        writeMenu.setEnabled(true);
        readMenu.setEnabled(true);
        followMenu.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        wrtPvtMsgPanel.setVisible(false);
        writeMenu.setEnabled(true);
        readMenu.setEnabled(true);
        followMenu.setEnabled(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        readPvtMsgPanel.setVisible(false);
        writeMenu.setEnabled(true);
        readMenu.setEnabled(true);
        followMenu.setEnabled(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        readPubMsgPanel.setVisible(false);
        writeMenu.setEnabled(true);
        readMenu.setEnabled(true);
        followMenu.setEnabled(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        hashtagSearchPanel.setVisible(false);
        writeMenu.setEnabled(true);
        readMenu.setEnabled(true);
        followMenu.setEnabled(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        youFollowPanel.setVisible(false);
        writeMenu.setEnabled(true);
        readMenu.setEnabled(true);
        followMenu.setEnabled(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        followYouPanel.setVisible(false);
        writeMenu.setEnabled(true);
        readMenu.setEnabled(true);
        followMenu.setEnabled(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        addFollowPanel.setVisible(false);
        writeMenu.setEnabled(true);
        readMenu.setEnabled(true);
        followMenu.setEnabled(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addFollowMenu;
    private javax.swing.JPanel addFollowPanel;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu followMenu;
    private javax.swing.JMenuItem followYouMenu;
    private javax.swing.JPanel followYouPanel;
    private javax.swing.JTextField hashtagField;
    private javax.swing.JButton hashtagSearchButton;
    private javax.swing.JMenuItem hashtagSearchMenu;
    private javax.swing.JPanel hashtagSearchPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JList<String> jList5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JMenuItem logOutMenu;
    private javax.swing.JMenu readMenu;
    private javax.swing.JMenuItem readPubMsgMenu;
    private javax.swing.JPanel readPubMsgPanel;
    private javax.swing.JPanel readPvtMsgPanel;
    private javax.swing.JMenuItem readYourMsgMenu;
    private javax.swing.JMenu writeMenu;
    private javax.swing.JMenuItem wrtPubMsgMenu;
    private javax.swing.JPanel wrtPubMsgPanel;
    private javax.swing.JMenuItem wrtPvtMsgMenu;
    private javax.swing.JPanel wrtPvtMsgPanel;
    private javax.swing.JMenuItem youFollowMenu;
    private javax.swing.JPanel youFollowPanel;
    // End of variables declaration//GEN-END:variables
}
